services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: adminer
      POSTGRES_PASSWORD: adminer
      POSTGRES_DB: adminer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: